# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
# print 'start'
# User.create(email: "tobby@example.com", password: "ayomide", name: "tobby")
# print 'end'

BudgetList.create([
	{
    'user_id': 2,
		'name': 'Rent',
		'amount': 1500.0,
		'status': 'Active',
		'category': 'Housing',
		'allow_overspending': false,
		'frequency': 'Monthly',
		'start_date': '2023-01-01',
		'end_date': '2023-12-31',
		'notes': 'Monthly rent for apartment',
	},
	{
    'user_id': 2,
		'name': 'Groceries',
		'amount': 300.0,
		'status': 'Active',
		'category': 'Food',
		'allow_overspending': false,
		'frequency': 'Monthly',
		'start_date': '2023-09-01',
		'end_date': '2023-09-30',
		'notes': 'Monthly grocery budget',
	},
	{
    'user_id': 2,
		'name': 'Vacation',
		'amount': 2000.0,
		'status': 'Planned',
		'category': 'Travel',
		'start_date': '2023-11-15',
		'end_date': '2023-11-30',
		'notes': 'Winter vacation planning',
	},
	{
    'user_id': 2,
		'name': 'Emergency Fund',
		'amount': 5000.0,
		'status': 'Active',
		'category': 'Savings',
		'allow_overspending': false,
		'frequency': 'Monthly',
		'start_date': '2023-01-01',
		'end_date': 'none',
		'notes': 'Savings for unexpected expenses',
	},
	{
    'user_id': 2,
		'name': 'Utilities',
		'amount': 400.0,
		'status': 'Active',
		'category': 'Bills',
		'allow_overspending': false,
		'frequency': 'Monthly',
		'start_date': '2023-09-01',
		'end_date': '2023-09-30',
		'notes': 'Monthly utility bills',
	},
	{
    'user_id': 2,
		'name': 'Car Maintenance',
		'amount': 100.0,
		'status': 'Active',
		'category': 'Transportation',
		'allow_overspending': false,
		'frequency': 'Monthly',
		'start_date': '2023-09-01',
		'end_date': '2023-09-30',
		'notes': 'Monthly car maintenance budget',
	},
	{
    'user_id': 2,
		'name': 'Entertainment',
		'amount': 200.0,
		'status': 'Active',
		'category': 'Entertainment',
		'allow_overspending': false,
		'frequency': 'Monthly',
		'start_date': '2023-09-01',
		'end_date': '2023-09-30',
		'notes': 'Monthly entertainment budget',
	},
	{
    'user_id': 2,
		'name': 'Healthcare',
		'amount': 150.0,
		'status': 'Active',
		'category': 'Health',
		'allow_overspending': false,
		'frequency': 'Monthly',
		'start_date': '2023-09-01',
		'end_date': '2023-09-30',
		'notes': 'Monthly healthcare expenses',
	},
	{
    'user_id': 2,
		'name': 'Education',
		'amount': 300.0,
		'status': 'Active',
		'allow_overspending': false,
		'frequency': 'Monthly',
		'category': 'Education',
		'start_date': '2023-09-01',
		'end_date': '2023-09-30',
		'notes': 'Monthly education expenses',
	},
	{
    'user_id': 2,
		'name': 'Vacation 2',
		'amount': 2500.0,
		'status': 'Planned',
		'allow_overspending': false,
		'frequency': 'Monthly',
		'category': 'Travel',
		'start_date': '2023-12-01',
		'end_date': '2023-12-15',
		'notes': 'Summer vacation planning',
	},
	{
    'user_id': 2,
		'name': 'Clothing',
		'amount': 200.0,
		'status': 'Active',
		'category': 'Shopping',
		'allow_overspending': false,
		'frequency': 'Monthly',
		'start_date': '2023-09-01',
		'end_date': '2023-09-30',
		'notes': 'Monthly clothing budget',
	},
	{
    'user_id': 2,
		'name': 'Emergency Fund 2',
		'amount': 7000.0,
		'status': 'Active',
		'category': 'Savings',
		'allow_overspending': false,
		'frequency': 'Monthly',
		'start_date': '2023-01-01',
		'end_date': 'none',
		'notes': 'Savings for unexpected expenses',
	},
	{
    'user_id': 2,
		'name': 'Home Improvement',
		'amount': 500.0,
		'status': 'Planned',
		'category': 'Housing',
		'allow_overspending': false,
		'frequency': 'Monthly',
		'start_date': '2023-10-01',
		'end_date': '2023-12-31',
		'notes': 'Renovation and repairs',
	},
	{
    'user_id': 2,
		'name': 'Fitness',
		'amount': 100.0,
		'status': 'Active',
		'category': 'Health',
		'allow_overspending': false,
		'frequency': 'Weekly',
		'start_date': '2023-09-01',
		'end_date': '2023-09-30',
		'notes': 'Monthly fitness expenses',
	},
	{
    'user_id': 2,
		'name': 'Gifts',
		'amount': 150.0,
		'status': 'Planned',
		'category': 'Miscellaneous',
		'allow_overspending': false,
		'frequency': 'Bi-weekly',
		'start_date': '2023-11-01',
		'end_date': '2023-12-31',
		'notes': 'Gift budget for holidays',
	},
	{
    'user_id': 2,
		'name': 'Investments',
		'amount': 1000.0,
		'status': 'Active',
		'category': 'Savings',
		'allow_overspending': false,
		'frequency': 'Weekly',
		'start_date': '2023-01-01',
		'end_date': 'none',
		'notes': 'Investing for the future',
	},
	{
    'user_id': 2,
		'name': 'Charity',
		'amount': 50.0,
		'status': 'Active',
		'category': 'Donations',
		'allow_overspending': true,
		'frequency': 'Weekly',
		'start_date': '2023-09-01',
		'end_date': '2023-09-30',
		'notes': 'Monthly charitable donations',
	},
	{
    'user_id': 2,
		'name': 'Electronics',
		'amount': 200.0,
		'status': 'Planned',
		'category': 'Shopping',
		'start_date': '2023-10-01',
		'end_date': '2023-12-31',
		'notes': 'Upgrade electronic devices',
	},
	{
		'name': 'Pet Care',
		'amount': 75.0,
		'status': 'Active',
		'category': 'Pets',
		'allow_overspending': false,
		'frequency': 'Weekly',
		'start_date': '2023-10-01',
		'end_date': '2023-12-31',
		'notes': 'Upgrade electronic devices',
    'user_id': 2,
	},
])